static const char black[]       = "#171B20";
static const char white[]       = "#cbced3";
static const char gray2[]       = "#2e323a"; // unfocused window border
static const char gray3[]       = "#1E222A";
static const char gray4[]       = "#6d8dad";
static const char blue[]        = "#86aaec";  // focused window border
static const char green[]       = "#90ceaa";
static const char red[]         = "#dd6777";
static const char orange[]      = "#caaa6a";
static const char yellow[]      = "#ecd3a0";
static const char pink[]        = "#c296eb";
static const char col_borderbar[]  = "#1e222a"; // inner border
